parameterize backupdir and fallback to prompt

diff --git a/src/backscrub b/src/backscrub
--- a/src/backscrub
+++ b/src/backscrub
@@ -1,15 +1,7 @@
 #!/usr/bin/env bash
 
-if [[ -f "$HOME"/bin/tsutils ]]; then
-    source "$HOME"/bin/tsutils
-else
-    echo "Cannot find tsutils library. Aborting."
-    exit 1
-fi
-
 SELF="$(basename "$0")"
 LOG="/var/log/$SELF-$(date +%Y.%m.%d).log"
-BACKUPDIR=/srv/backups/mac/Users
 BACKUPS=($BACKUPDIR/*)
 GROUP="Users_UKGroupSeniorManagement"
 KEY11=()
@@ -25,6 +17,23 @@ sort_array () {
     IFS=$'\n'
     KEY11=($(sort <<<"${KEY11[*]}"))
     unset IFS
+}
+
+get_lib () {
+    if [[ -f "$HOME"/bin/tsutils ]]; then
+	source "$HOME"/bin/tsutils
+    else
+	echo "Cannot find tsutils library. Aborting."
+	exit 1
+    fi
+}
+
+get_backupdir () {
+    read -rep "Enter a backup directory: " BACKUPDIR
+}
+
+get_days () {
+    read -rep "Enter a number of days: " DAYS
 }
 
 get_key11 () {
@@ -61,12 +70,10 @@ remove_key11 () {
 }
 
 get_olddirs () {
-    local days="$1"
-
     for d in "${BACKUPS[@]}"; do
 	while IFS=  read -r -d $'\0' path; do
 	    OLDBACKUPS+=("$path")
-	done < <(find "$d" -maxdepth 1 -mindepth 1 -type d -mtime +"$days" -print0)
+	done < <(find "$d" -maxdepth 1 -mindepth 1 -type d -mtime +"$DAYS" -print0)
     done
 }
 
@@ -91,15 +98,15 @@ delete_olddirs () {
 }
 
 main () {
-    local days="$1" total=0
+    local total=0
+
+    get_lib
+
+    [[ -z "$1" ]] && get_backdir || BACKUPDIR="$1"
+    [[ -z "$2" ]] && get_days || DAYS="$2"
 
     chkroot
-
-    if [[ -z "$days" ]]; then
-	usage
-	exit 1
-    fi
-
+    chkdirs || { usage; exit 1; }
     mkplate "$LOG" "$SELF" "Start"
 
     echo "Searching for Key 11 users in AD (might take a while)..."
@@ -109,11 +116,11 @@ main () {
     log_key11
     remove_key11
 
-    echo "Getting directories in $BACKUPDIR older than $days days..." | tee -a "$LOG"
-    get_olddirs "$days"
+    echo "Getting directories in $BACKUPDIR older than $DAYS days..." | tee -a "$LOG"
+    get_olddirs "$DAYS"
     delete_olddirs
 
     mkplate "$LOG" "$SELF" "Finish"
 }
 
-main "$1"
+main "$@"
